export {IoIosMenu, IoIosArrowForward} from 'react-icons/io';
export {IoSearchOutline, IoSettingsOutline} from 'react-icons/io5';
export {AiFillHome, AiOutlineHome, AiFillClockCircle, AiOutlineClockCircle, AiOutlineHistory, AiOutlineLogout} from 'react-icons/ai';
export {RiThumbUpFill, RiThumbUpLine, RiFolderHistoryLine} from 'react-icons/ri';
export {MdVideoLibrary, MdOutlineVideoLibrary} from 'react-icons/md';
export {CgProfile, CgPlayListAdd} from 'react-icons/cg';
export {BiDotsVerticalRounded} from 'react-icons/bi';
export {BsSun, BsMoon} from 'react-icons/bs';
export {BiShare} from 'react-icons/bi';
export {FaRegTrashAlt} from 'react-icons/fa';