export {IoIosMenu, IoIosArrowForward,IoMdClose, IoMdAdd} from 'react-icons/io';
export {IoSearchOutline} from 'react-icons/io5';
export {AiFillHome, AiOutlineHome, AiFillClockCircle, AiOutlineClockCircle, AiOutlineHistory, AiOutlineLogout} from 'react-icons/ai';
export {RiThumbUpFill, RiThumbUpLine, RiFolderHistoryLine, RiPlayList2Fill} from 'react-icons/ri';
export {MdVideoLibrary, MdOutlineVideoLibrary, MdFaceRetouchingOff, MdFace, MdOutlineFlipCameraIos} from 'react-icons/md';
export {CgProfile, CgPlayListAdd} from 'react-icons/cg';
export {BiDotsVerticalRounded, BiMask} from 'react-icons/bi';
export {BsSun, BsMoon, BsEyeFill, BsEyeSlashFill} from 'react-icons/bs';
export {BiShare} from 'react-icons/bi';
export {FaRegTrashAlt} from 'react-icons/fa';